set_property PACKAGE_PIN K17 [get_ports VCAP_B2]
set_property PACKAGE_PIN F20 [get_ports VCAP_B1]
set_property PACKAGE_PIN F19 [get_ports VCAP_B0]
set_property PACKAGE_PIN M20 [get_ports VCAP_R2]
set_property PACKAGE_PIN M19 [get_ports VCAP_R1]
set_property PACKAGE_PIN G14 [get_ports VCAP_R0]
set_property PACKAGE_PIN N15 [get_ports VCAP_R3]
set_property PACKAGE_PIN H17 [get_ports VCAP_G3]
set_property PACKAGE_PIN K18 [get_ports VCAP_B3]
set_property PACKAGE_PIN E18 [get_ports VCAP_B4]
set_property PACKAGE_PIN E19 [get_ports VCAP_B5]
set_property PACKAGE_PIN E17 [get_ports VCAP_B6]
set_property PACKAGE_PIN D18 [get_ports VCAP_B7]
set_property PACKAGE_PIN B19 [get_ports VCAP_G0]
set_property PACKAGE_PIN A20 [get_ports VCAP_G1]
set_property PACKAGE_PIN H16 [get_ports VCAP_G2]
set_property PACKAGE_PIN N16 [get_ports VCAP_R4]
set_property PACKAGE_PIN H15 [get_ports VCAP_G4]
set_property PACKAGE_PIN J20 [get_ports VCAP_R5]
set_property PACKAGE_PIN G15 [get_ports VCAP_G5]
set_property PACKAGE_PIN H20 [get_ports VCAP_R6]
set_property PACKAGE_PIN M14 [get_ports VCAP_G6]
set_property PACKAGE_PIN C20 [get_ports VCAP_R7]
set_property PACKAGE_PIN M15 [get_ports VCAP_G7]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_ADDR[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ZORRO_DATA[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_ADDRDIR]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_DATADIR]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_ADDRDIR2]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NBRN]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NBGN]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_C28D]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_READ]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_DOE]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NDS0]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NDS1]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NLDS]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NUDS]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NFCS]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NCCS]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NSLAVE]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NCINH]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NCFGIN]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NCFGOUT]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NDTACK]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_NIORST]
set_property IOSTANDARD LVCMOS33 [get_ports ZORRO_E7M]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ZORRO_E7M]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ZORRO_E7M_IBUF_BUFG]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ZORRO_E7M_IBUF]

set_property PACKAGE_PIN V20 [get_ports {ZORRO_DATA[15]}]
set_property PACKAGE_PIN W15 [get_ports {ZORRO_DATA[14]}]
set_property PACKAGE_PIN V15 [get_ports {ZORRO_DATA[13]}]
set_property PACKAGE_PIN T20 [get_ports {ZORRO_DATA[12]}]
set_property PACKAGE_PIN P20 [get_ports {ZORRO_DATA[11]}]
set_property PACKAGE_PIN N20 [get_ports {ZORRO_DATA[10]}]
set_property PACKAGE_PIN J15 [get_ports {ZORRO_DATA[9]}]
set_property PACKAGE_PIN L15 [get_ports {ZORRO_DATA[8]}]
set_property PACKAGE_PIN F17 [get_ports {ZORRO_DATA[7]}]
set_property PACKAGE_PIN F16 [get_ports {ZORRO_DATA[6]}]
set_property PACKAGE_PIN H18 [get_ports {ZORRO_DATA[5]}]
set_property PACKAGE_PIN K16 [get_ports {ZORRO_DATA[4]}]
set_property PACKAGE_PIN J16 [get_ports {ZORRO_DATA[3]}]
set_property PACKAGE_PIN K14 [get_ports {ZORRO_DATA[2]}]
set_property PACKAGE_PIN J14 [get_ports {ZORRO_DATA[1]}]
set_property PACKAGE_PIN L14 [get_ports {ZORRO_DATA[0]}]

set_property PACKAGE_PIN U9 [get_ports ZORRO_ADDRDIR]
set_property PACKAGE_PIN T15 [get_ports ZORRO_ADDRDIR2]
set_property PACKAGE_PIN U17 [get_ports ZORRO_NBRN]
set_property PACKAGE_PIN T14 [get_ports ZORRO_NBGN]
set_property PACKAGE_PIN B20 [get_ports ZORRO_C28D]
set_property PACKAGE_PIN Y12 [get_ports ZORRO_DATADIR]
set_property PACKAGE_PIN Y19 [get_ports ZORRO_READ]
set_property PACKAGE_PIN W10 [get_ports ZORRO_DOE]
#set_property PACKAGE_PIN C20 [get_ports ZORRO_NMTCR]
set_property PACKAGE_PIN Y14 [get_ports ZORRO_NDS0]
set_property PACKAGE_PIN W14 [get_ports ZORRO_NDS1]
set_property PACKAGE_PIN Y18 [get_ports ZORRO_NLDS]
set_property PACKAGE_PIN W20 [get_ports ZORRO_NUDS]
set_property PACKAGE_PIN V5 [get_ports ZORRO_NFCS]
set_property PACKAGE_PIN U13 [get_ports ZORRO_NCCS]
set_property PACKAGE_PIN U15 [get_ports ZORRO_NSLAVE]
set_property PACKAGE_PIN U14 [get_ports ZORRO_NCINH]
set_property PACKAGE_PIN W13 [get_ports ZORRO_NCFGIN]
set_property PACKAGE_PIN P14 [get_ports ZORRO_NCFGOUT]
set_property PACKAGE_PIN W9 [get_ports ZORRO_NDTACK]
set_property PACKAGE_PIN V12 [get_ports ZORRO_NIORST]
set_property PACKAGE_PIN R14 [get_ports ZORRO_E7M]

set_property PACKAGE_PIN Y13 [get_ports {ZORRO_ADDR[22]}]
set_property PACKAGE_PIN W11 [get_ports {ZORRO_ADDR[21]}]
set_property PACKAGE_PIN Y11 [get_ports {ZORRO_ADDR[20]}]
set_property PACKAGE_PIN Y9 [get_ports {ZORRO_ADDR[19]}]
set_property PACKAGE_PIN Y8 [get_ports {ZORRO_ADDR[18]}]
set_property PACKAGE_PIN Y7 [get_ports {ZORRO_ADDR[17]}]
set_property PACKAGE_PIN Y6 [get_ports {ZORRO_ADDR[16]}]
set_property PACKAGE_PIN T5 [get_ports {ZORRO_ADDR[15]}]
set_property PACKAGE_PIN U5 [get_ports {ZORRO_ADDR[14]}]
set_property PACKAGE_PIN W6 [get_ports {ZORRO_ADDR[13]}]
set_property PACKAGE_PIN V6 [get_ports {ZORRO_ADDR[12]}]
set_property PACKAGE_PIN W8 [get_ports {ZORRO_ADDR[11]}]
set_property PACKAGE_PIN V8 [get_ports {ZORRO_ADDR[10]}]
set_property PACKAGE_PIN V7 [get_ports {ZORRO_ADDR[9]}]
set_property PACKAGE_PIN U7 [get_ports {ZORRO_ADDR[8]}]
set_property PACKAGE_PIN U8 [get_ports {ZORRO_ADDR[7]}]
set_property PACKAGE_PIN U10 [get_ports {ZORRO_ADDR[6]}]
set_property PACKAGE_PIN T11 [get_ports {ZORRO_ADDR[5]}]
set_property PACKAGE_PIN V13 [get_ports {ZORRO_ADDR[4]}]
set_property PACKAGE_PIN V10 [get_ports {ZORRO_ADDR[3]}]
set_property PACKAGE_PIN T9 [get_ports {ZORRO_ADDR[2]}]
set_property PACKAGE_PIN T10 [get_ports {ZORRO_ADDR[1]}]
set_property PACKAGE_PIN V11 [get_ports {ZORRO_ADDR[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B7]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B6]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B5]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B4]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B3]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B2]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B1]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_B0]

set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R7]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R6]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R5]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R4]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R3]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R2]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R1]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_R0]

set_property IOSTANDARD LVCMOS33 [get_ports VCAP_VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_HSYNC]

set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G0]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G1]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G2]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G3]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G4]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G5]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G6]
set_property IOSTANDARD LVCMOS33 [get_ports VCAP_G7]



set_property PACKAGE_PIN Y17 [get_ports VCAP_VSYNC]
set_property PACKAGE_PIN Y16 [get_ports VCAP_HSYNC]


set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[7]}]

set_property PACKAGE_PIN D20 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN M17 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN M18 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN G17 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN G18 [get_ports {VGA_R[4]}]
set_property PACKAGE_PIN K19 [get_ports {VGA_R[5]}]
set_property PACKAGE_PIN J19 [get_ports {VGA_R[6]}]
set_property PACKAGE_PIN J18 [get_ports {VGA_R[7]}]

set_property PACKAGE_PIN V17 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN G19 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN G20 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN L19 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN L20 [get_ports {VGA_G[4]}]
set_property PACKAGE_PIN L16 [get_ports {VGA_G[5]}]
set_property PACKAGE_PIN L17 [get_ports {VGA_G[6]}]
set_property PACKAGE_PIN D19 [get_ports {VGA_G[7]}]

set_property PACKAGE_PIN W19 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN W18 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN P19 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN N18 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN T19 [get_ports {VGA_B[4]}]
set_property PACKAGE_PIN R19 [get_ports {VGA_B[5]}]
set_property PACKAGE_PIN P15 [get_ports {VGA_B[6]}]
set_property PACKAGE_PIN P16 [get_ports {VGA_B[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports VGA_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_DE]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN R17 [get_ports VGA_VS]
set_property PACKAGE_PIN R16 [get_ports VGA_HS]
set_property PACKAGE_PIN N17 [get_ports VGA_DE]
set_property PACKAGE_PIN V18 [get_ports VGA_PCLK]

#set_property IOSTANDARD LVCMOS33 [get_ports HDMI_INTN]
#set_property PACKAGE_PIN W19 [get_ports HDMI_INTN]

#set_property PACKAGE_PIN B9 [get_ports I2C0_sda_io]
#set_property PACKAGE_PIN B13 [get_ports I2C0_scl_io]
#set_property IOSTANDARD LVCMOS33 [get_ports I2C0_scl_io]
#set_property IOSTANDARD LVCMOS33 [get_ports I2C0_sda_io]
#set_property PULLUP true [get_ports I2C0_sda_io]
#set_property PULLUP true [get_ports I2C0_scl_io]

create_clock -period 143.000 -name amiga_e7m -add [get_ports ZORRO_E7M]

set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins zz9000_ps_i/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/plle2_adv_inst/CLKOUT0]]

set_false_path -from [get_clocks -of_objects [get_pins zz9000_ps_i/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks clk_fpga_0]

set_false_path -from [get_clocks amiga_e7m] -to [get_clocks clk_fpga_0]
